<a href="https://colab.research.google.com/github/anytaaly/Pandas-Numpy-Pytorch/blob/main/pandas_numpy_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import os


from google.colab import userdata

In [ ]:
os.environ['KAGGLE_USERNAME'] = userdata.get('KAGGLE_USERNAME')
os.environ['KAGGLE_KEY'] = userdata.get('KAGGLE_KEY')

In [ ]:
!kaggle config view

Configuration values from /root/.config/kaggle
- username: anytaal
- auth_method: LEGACY_API_KEY
- path: None
- proxy: None
- competition: None

In [ ]:
!kaggle datasets download -d pratyushakar/rossmann-store-sales

Dataset URL: https://www.kaggle.com/datasets/pratyushakar/rossmann-store-sales
License(s): CC0-1.0
Downloading rossmann-store-sales.zip to /content
100% 6.90M/6.90M [00:01<00:00, 5.90MB/s]

In [ ]:
!unzip -o rossmann-store-sales.zip

Archive:  rossmann-store-sales.zip
  inflating: store.csv
  inflating: test.csv
  inflating: train.csv

In [ ]:

# read train file
df = pd.read_csv('train.csv', low_memory=False)

# Pandas Series vs. Pandas Dataframe

A Series is a one-dimensional array0like object, while a DataFrame is a two-dimensional table.

Building Blocks: A DataFrame is essentially a container for multiple Series objects. Each column in a Pandas DataFrame is technically a Pandas Series.

In [ ]:
df.shape

(1017209, 9)

In [ ]:
df.columns

Index(['Store', 'DayOfWeek', 'Date', 'Sales', 'Customers', 'Open', 'Promo',
       'StateHoliday', 'SchoolHoliday'],
      dtype='object')

In [ ]:
df.head()

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday
0,1,5,2015-07-31,5263,555,1,1,0,1
1,2,5,2015-07-31,6064,625,1,1,0,1
2,3,5,2015-07-31,8314,821,1,1,0,1
3,4,5,2015-07-31,13995,1498,1,1,0,1
4,5,5,2015-07-31,4822,559,1,1,0,1

In [ ]:
store = pd.read_csv('store.csv', low_memory=False)

In [ ]:
store.columns

Index(['Store', 'StoreType', 'Assortment', 'CompetitionDistance',
       'CompetitionOpenSinceMonth', 'CompetitionOpenSinceYear', 'Promo2',
       'Promo2SinceWeek', 'Promo2SinceYear', 'PromoInterval'],
      dtype='object')

In [ ]:
store['Promo2']

0       0
1       1
2       1
3       0
4       0
       ..
1110    1
1111    0
1112    0
1113    0
1114    1
Name: Promo2, Length: 1115, dtype: int64

In [ ]:
store[['Promo2', 'Promo2SinceWeek']]

      Promo2  Promo2SinceWeek
0          0              NaN
1          1             13.0
2          1             14.0
3          0              NaN
4          0              NaN
...      ...              ...
1110       1             31.0
1111       0              NaN
1112       0              NaN
1113       0              NaN
1114       1             22.0

[1115 rows x 2 columns]

In [ ]:
# Filtering rows df[df['Column'] == value]           # single condition
store[store['Promo2']==1]

,Store,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
1,2,a,a,570.0,11.0,2007.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct"
2,3,a,a,14130.0,12.0,2006.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
10,11,a,c,960.0,11.0,2011.0,1,1.0,2012.0,"Jan,Apr,Jul,Oct"
11,12,a,c,1070.0,NaN,NaN,1,13.0,2010.0,"Jan,Apr,Jul,Oct"
12,13,d,a,310.0,NaN,NaN,1,45.0,2009.0,"Feb,May,Aug,Nov"
...,...,...,...,...,...,...,...,...,...,...
1105,1106,a,c,5330.0,9.0,2011.0,1,31.0,2013.0,"Jan,Apr,Jul,Oct"
1106,1107,a,a,1400.0,6.0,2012.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct"
1108,1109,c,a,3490.0,4.0,2011.0,1,22.0,2012.0,"Jan,Apr,Jul,Oct"
1110,1111,a,a,1900.0,6.0,2014.0,1,31.0,2013.0,"Jan,Apr,Jul,Oct"
1114,1115,d,c,5350.0,NaN,NaN,1,22.0,2012.0,"Mar,Jun,Sept,Dec"

In [ ]:
#Filtering rows df[df['Column'] == value]  df[(df['Col1'] == val1) & (df['Col2'] == val2)]   # AND

store[(store['Store'] == 1) & (store['Assortment'] == 'a')]

,Store,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
0,1,c,a,1270.0,9.0,2008.0,0,NaN,NaN,NaN

In [ ]:
store[(store['Assortment'] == 'b') | (store['Assortment'] == 'a')]

,Store,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
0,1,c,a,1270.0,9.0,2008.0,0,NaN,NaN,NaN
1,2,a,a,570.0,11.0,2007.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct"
2,3,a,a,14130.0,12.0,2006.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
4,5,a,a,29910.0,4.0,2015.0,0,NaN,NaN,NaN
5,6,a,a,310.0,12.0,2013.0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
1103,1104,d,a,260.0,2.0,2012.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
1106,1107,a,a,1400.0,6.0,2012.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct"
1107,1108,a,a,540.0,4.0,2004.0,0,NaN,NaN,NaN
1108,1109,c,a,3490.0,4.0,2011.0,1,22.0,2012.0,"Jan,Apr,Jul,Oct"
1110,1111,a,a,1900.0,6.0,2014.0,1,31.0,2013.0,"Jan,Apr,Jul,Oct"

In [ ]:
# df[~(df['Column'] == value)]        # NOT

In [ ]:
# Combining row filter + column select
store[store['StoreType'] == 'a' ][['CompetitionDistance', 'CompetitionOpenSinceMonth']]

      CompetitionDistance  CompetitionOpenSinceMonth
1                   570.0                       11.0
2                 14130.0                       12.0
4                 29910.0                        4.0
5                   310.0                       12.0
6                 24000.0                        4.0
...                   ...                        ...
1106               1400.0                        6.0
1107                540.0                        4.0
1110               1900.0                        6.0
1112               9260.0                        NaN
1113                870.0                        NaN

[602 rows x 2 columns]

In [ ]:
len(store)

1115

In [ ]:
# value_counts()
# Counts the frequency of each unique value in a column — returns a breakdown:
store['Store'].value_counts()

Store
1115    1
1       1
2       1
3       1
4       1
       ..
16      1
15      1
14      1
13      1
12      1
Name: count, Length: 1115, dtype: int64

In [ ]:
store['Store'].unique()

array([   1,    2,    3, ..., 1113, 1114, 1115])

# Data Vizualization

What Type of data are you working with?

* **Time-Series** : data that spans across continuius time period)
Area Chart

* **Categorical** : Data that can be split up into groups or categories.Pie Chart - Sort the slices, Keep them under ~ 5 and focus on one.

Heat Map, Bar Chart, 100% stacked

* **Numeric** : Data with quantitative values, etiher discrete or continuous.

Line Chart (The dates must be continuous)
Scatter Plot

* **Hierarchical** : Data that has natural groups and sub-groups.


What do you want to communicate?

* **Comparison** Compares values over time or across categories. it can answer questions like: So are we interested in visualizing whether or not our sales this year were greater than last year or Are we interested in determining if our store in New York City is outperforming our store in Los Angeles.

Line Chart ,
Bar Chart (baseline must start at zero) ,
Area Chart ,
100% stacked

* **Composition** Breaks down the component parts of a whole. So instead of comparing our sales in New York directly to our sales in Los Angeles, we might want to understand how each store contributes to our overall sales.

Pie Chart - Sort the slices, Keep them under ~ 5 and focus on one,
100% stacked

* **distribution** Shows the frequency of values within a series.
We might also be interested in looking at the distribution of our data. So which values in our data are rare?Which values are common? What's the mean What's the median? What's the 25th percentile, etc.?

Histogram (avoid using too many bins) ,


* **Relationship** Shows the correlation between multiple variables.
So as our sales in New York City rise to our sales in Los Angeles see a similar increase, are they for some reason decreasing?

Scatter Plot : Remember that correkation does not imply causation.


Who is the end user and what do they need?
* Analyst
* Manager
* Executive

  ![](https://drive.google.com/uc?export=view&id=1HkMXeGE1nhtxVKn_MP_Tv6BRwpnzHCge)

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
hotels = pd.read_excel('/content/HotelCustomersDataset.xlsx')

In [ ]:
hotels.head()

,ID,Nationality,Age,DaysSinceCreation,AverageLeadTime,LodgingRevenue,OtherRevenue,BookingsCanceled,BookingsNoShowed,BookingsCheckedIn,...,SRMediumFloor,SRBathtub,SRShower,SRCrib,SRKingSizeBed,SRTwinBed,SRNearElevator,SRAwayFromElevator,SRNoAlcoholInMiniBar,SRQuietRoom
0,1,PRT,51.0,150,45,371.0,105.3,1,0,3,...,0,0,0,0,0,0,0,0,0,0
1,2,PRT,NaN,1095,61,280.0,53.0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,3,DEU,31.0,1095,0,0.0,0.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,FRA,60.0,1095,93,240.0,60.0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,5,FRA,51.0,1095,0,0.0,0.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
hotels.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83590 entries, 0 to 83589
Data columns (total 29 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ID                    83590 non-null  int64
 1   Nationality           83590 non-null  object
 2   Age                   79811 non-null  float64
 3   DaysSinceCreation     83590 non-null  int64
 4   AverageLeadTime       83590 non-null  int64
 5   LodgingRevenue        83590 non-null  float64
 6   OtherRevenue          83590 non-null  float64
 7   BookingsCanceled      83590 non-null  int64
 8   BookingsNoShowed      83590 non-null  int64
 9   BookingsCheckedIn     83590 non-null  int64
 10  PersonsNights         83590 non-null  int64
 11  RoomNights            83590 non-null  int64
 12  DaysSinceLastStay     83590 non-null  int64
 13  DaysSinceFirstStay    83590 non-null  int64
 14  DistributionChannel   83590 non-null  object
 15  MarketSegment         83590 non-null  object
 16  SRHighFloor           83590 non-null  int64
 17  SRLowFloor            83590 non-null  int64
 18  SRAccessibleRoom      83590 non-null  int64
 19  SRMediumFloor         83590 non-null  int64
 20  SRBathtub             83590 non-null  int64
 21  SRShower              83590 non-null  int64
 22  SRCrib                83590 non-null  int64
 23  SRKingSizeBed         83590 non-null  int64
 24  SRTwinBed             83590 non-null  int64
 25  SRNearElevator        83590 non-null  int64
 26  SRAwayFromElevator    83590 non-null  int64
 27  SRNoAlcoholInMiniBar  83590 non-null  int64
 28  SRQuietRoom           83590 non-null  int64
dtypes: float64(3), int64(23), object(3)
memory usage: 18.5+ MB

In [ ]:
hotels.count()

ID                      83590
Nationality             83590
Age                     79811
DaysSinceCreation       83590
AverageLeadTime         83590
LodgingRevenue          83590
OtherRevenue            83590
BookingsCanceled        83590
BookingsNoShowed        83590
BookingsCheckedIn       83590
PersonsNights           83590
RoomNights              83590
DaysSinceLastStay       83590
DaysSinceFirstStay      83590
DistributionChannel     83590
MarketSegment           83590
SRHighFloor             83590
SRLowFloor              83590
SRAccessibleRoom        83590
SRMediumFloor           83590
SRBathtub               83590
SRShower                83590
SRCrib                  83590
SRKingSizeBed           83590
SRTwinBed               83590
SRNearElevator          83590
SRAwayFromElevator      83590
SRNoAlcoholInMiniBar    83590
SRQuietRoom             83590
dtype: int64

In [ ]:
#value_counts() is a popular Pandas method used to compute the frequency of unique values in a dataset
hotels.value_counts()

ID     Nationality  Age   DaysSinceCreation  AverageLeadTime  LodgingRevenue  OtherRevenue  BookingsCanceled  BookingsNoShowed  BookingsCheckedIn  PersonsNights  RoomNights  DaysSinceLastStay  DaysSinceFirstStay  DistributionChannel    MarketSegment          SRHighFloor  SRLowFloor  SRAccessibleRoom  SRMediumFloor  SRBathtub  SRShower  SRCrib  SRKingSizeBed  SRTwinBed  SRNearElevator  SRAwayFromElevator  SRNoAlcoholInMiniBar  SRQuietRoom
83590  IRL          13.0  0                  0                0.0             0.0           0                 0                 0                  0              0           -1                 -1                  Travel Agent/Operator  Other                  0            0           0                 0              0          0         0       0              1          0               0                   0                     0              1
1      PRT          51.0  150                45               371.0           105.3         1                 0                 3                  8              5            151                1074               Corporate              Corporate              0            0           0                 0              0          0         0       0              0          0               0                   0                     0              1
3      DEU          31.0  1095               0                0.0             0.0           0                 0                 0                  0              0           -1                 -1                  Travel Agent/Operator  Travel Agent/Operator  0            0           0                 0              0          0         0       0              0          0               0                   0                     0              1
83574  FRA          36.0  0                  0                0.0             0.0           0                 0                 0                  0              0           -1                 -1                  Travel Agent/Operator  Travel Agent/Operator  0            0           0                 0              0          0         0       0              0          0               0                   0                     0              1
83573  PRT          33.0  0                  93               252.0           200.0         0                 0                 1                  8              4            4                  4                  Travel Agent/Operator  Travel Agent/Operator  0            0           0                 0              0          0         0       0              0          0               0                   0                     0              1
                                                                                                                                                                                                                                                                                                                                                                                                                                                            ..
9      FRA          42.0  1095               0                0.0             0.0           0                 0                 0                  0              0           -1                 -1                  Travel Agent/Operator  Other                  0            0           0                 0              0          0         0       1              0          0               0                   0                     0              1
8      FRA          32.0  1095               38               535.0           94.0          0                 0                 1                  10             5            1100               1100               Travel Agent/Operator  Other                  0            0           0                 0              0          0         0       1              0          0               0                   0                     0              1
7      JPN          49.0  1095               0                0.0             0.0           0                 0                 0                  0              0           -1                 -1                  Travel Agent/Operator  Other                  0            0           0                 0              0          0         0       0              0          0               0                   0                     0              1
6      JPN          54.0  1095               58               230.0           24.0          0                 0                 1                  4              2            1097               1097               Travel Agent/Operator  Other                  0            0           0                 0              0          0         0       0              0          0               0                   0                     0              1
5      FRA          51.0  1095               0                0.0             0.0           0                 0                 0                  0              0           -1                 -1                  Travel Agent/Operator  Travel Agent/Operator  0            0           0                 0              0          0         0       0              0          0               0                   0                     0              1
Name: count, Length: 79811, dtype: int64

In [ ]:
# Assignment 1: Subplots

# Plot The distribution of lodging revenue for our top 5 countries by revenue ("PRT, "ESP", "FRA", "DEU", "GBR").
# **Limit Data to Bookings with RoomNights < 15**

# Make sure to share both x and y axes and give them titles!

# Remove the extra chart with `ax[row, col].set_axis_off()` if using plt.subplots()

#create the date column since it doenst exist:
hotels["date"] = (pd.to_datetime("2018-12-31") - pd.to_timedelta(hotels["DaysSinceCreation"], unit='D')).astype("datetime64[ns]")

In [ ]:
hotels["date"]

0       2018-08-03
1       2016-01-01
2       2016-01-01
3       2016-01-01
4       2016-01-01
           ...
83585   2018-12-31
83586   2018-12-31
83587   2018-12-31
83588   2018-12-31
83589   2018-12-31
Name: date, Length: 83590, dtype: datetime64[ns]

In [ ]:
# Plot The distribution of lodging revenue for our top 5 countries by revenue ("PRT, "ESP", "FRA", "DEU", "GBR").
# **Limit Data to Bookings with RoomNights < 15**
df_revenue = hotels.groupby(['Nationality'])[['LodgingRevenue','OtherRevenue']].sum()

In [ ]:
df_revenue

             LodgingRevenue  OtherRevenue
Nationality
ABW                 1896.52        256.70
AGO                96436.72      18737.77
AIA                 1164.60        125.50
ALB                 3455.90        811.98
AND                 3107.40        652.85
...                     ...           ...
WLF                  135.20          2.00
WSM                  314.00         28.00
YEM                    0.00          0.00
ZAF                20328.68       3214.93
ZWE                  684.00         54.00

[188 rows x 2 columns]